name: Test Clever Cloud action

on:
  push:
    branches:
      - clever

jobs:
  cc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: release-tag
        name: Generate release tag
        run: echo "tag=${{ github.ref_name }}@$(date +%Y-%m-%d_%H.%M.%S)_$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT
      - id: docker-tag
        run: |
          tag=$(                        \
            echo ${{ github.ref_name }} \
            | sed 's#refs/heads/##g'    \
            | sed 's#refs/tags/##g'     \
            | sed 's#refs/pull/##g'     \
            | tr '/' '_'                \
            | tr -d '#'                 \
          )
          if [ "$tag" == "master" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=$tag" >> $GITHUB_OUTPUT
          fi
      - run: echo ${{ steps.docker-tag.outputs.tag }}
      - uses: 47ng/actions-clever-cloud@v2.0.0
        name: Deploy to Clever Cloud
        with:
          appID: app_6830cbcd-3cf0-48c2-952d-af1425b7d901
          setEnv: |
            RELEASE_TAG=${{ steps.release-tag.outputs.tag }}
            INDEX=2
            with_equals=k1.aesgcm256.NS5wL0fSYZObRHddlB-sNP28Hw1EJKVYqnpCtOjaTAE=
            FAIL=false
            BUILD_URL=https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
            CC_POST_BUILD_HOOK=yarn run annotate
          logFile: ./clever.log
          quiet: false
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
      - uses: actions/upload-artifact@v4
        name: Upload deployment logs
        with:
          name: clever.log
          path: ./clever.log
          retention-days: 1
