name: Test Clever Cloud action

on:
  push:

jobs:
  cc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: release-tag
        name: Generate release tag
        run: echo "::set-output name=value::${{ github.ref_name }}@$(date +%Y-%m-%d_%H.%M.%S)_$(echo $GITHUB_SHA | cut -c1-8)"
      - uses: docker://47ng/actions-clever-cloud:feat-logs
        name: Deploy to Clever Cloud
        with:
          appID: app_6830cbcd-3cf0-48c2-952d-af1425b7d901
          setEnv: |
            RELEASE_TAG=${{ steps.release-tag.outputs.value }}
            # Some comment here
            123=456
            with_equals=k1.aesgcm256.NS5wL0fSYZObRHddlB-sNP28Hw1EJKVYqnpCtOjaTAE=
            FAIL=false
            BUILD_URL=https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
            CC_POST_BUILD_HOOK=yarn run annotate

            Technically, we can also have plain-text docs, as long as they
            don't contain an equals sign.
          force: true
          logFile: ${{ github.workspace }}/clever.log
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
      - uses: actions/upload-artifact@v2
        name: Upload deployment logs
        with:
          name: clever.log
          path: clever.log
          retention-days: 1
