name: Test Clever Cloud action

on:
  push:

jobs:
  cc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - run: git fetch --prune --unshallow # Required for Clever Cloud deployments
      - id: release-tag
        name: Generate release tag
        run: echo "::set-output name=value::${{ github.ref_name }}@$(date +%Y-%m-%d_%H.%M.%S)_$(echo $GITHUB_SHA | cut -c1-8)"
      - uses: docker://47ng/actions-clever-cloud:latest
        name: Deploy to Clever Cloud
        with:
          appID: app_7dba9ffa-f243-469a-8aa0-c0be3fcaa88f
          timeout: 600 # 10 minutes
          setEnv: |
            RELEASE_TAG=${{ steps.release-tag.outputs.value }}
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
