name: Comment to PR

on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
    - run: echo ${{ toJSON(github.event) }}
    - run: echo ${{ toJSON(env) }}
    
