name: Comment to PR

on:
  issue_comment:
    types: [created, edited]

jobs:
  commentToPR:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
    - name: Add initial reaction (processing)
      uses: peter-evans/create-or-update-comment@5221bf4aa615e5c6e95bb142f9673a9c791be2cd
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: eyes
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
      with:
        node-version: 14.x
    - uses: DamianReeves/write-file-action@e19fd875ed54f16fc583a3486e62547ce4a5dde8
      with:
        path: "${{ github.workspace }}/commentToPR/${{ github.event.comment.id }}.md"
        contents: ${{ github.event.comment.body }}
        write-mode: append
    - run: ls -la ./commentToPR
    - run: cat "./commentToPR/${{ github.event.comment.id }}.md"
    - uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: "commentToPR/${{ github.event.comment.id }}"
        delete-branch: true
        title: "Submission by ${{ github.event.comment.user.login }}"
        body: "${{ github.event.comment.body }}"
        commit-message: "Submission by ${{ github.event.comment.user.login }}"
    - name: Add final reaction (failed)
      if: ${{ failure() }}
      uses: peter-evans/create-or-update-comment@5221bf4aa615e5c6e95bb142f9673a9c791be2cd
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: confused
    - name: Add final reaction (success)
      if: ${{ success() }}
      uses: peter-evans/create-or-update-comment@5221bf4aa615e5c6e95bb142f9673a9c791be2cd
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: '+1'










