name: Comment to PR

on:
  issue_comment:
    types: [created]

jobs:
  commentToPR:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
      with:
        node-version: 14.x
    - uses: DamianReeves/write-file-action@v1
      with:
        path: "${{ github.workspace }}/commentToPR/${{ github.event.comment.id }}.md"
        contents: ${{ github.event.comment.body }}
        write-mode: append
    - run: ls -la ./commentToPR
    - run: cat "./commentToPR/${{ github.event.comment.id }}.md"
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: "commentToPR/${{ github.event.comment.id }}"
        delete-branch: true
        title: "Submission by ${{ github.event.comment.user.login }}"
        body: "${{ github.event.comment.body }}"
