name: Comment to PR

on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
      with:
        node-version: 14.x
    - run: echo "${{ toJSON(github.event) }}"
    - run: echo "${{ github.event.comment.body }}" > "./commentToPR/${{ github.event.comment.id }}.md"
    - run: ls -la ./commentToPR
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: "commentToPR/${{ github.event.comment.id }}"
        delete-branch: true
        title: "Submission by ${{ github.event.comment.user.login }}"
        body: "${{ github.event.comment.body }}"
