name: Discussion to file

on:
  discussion:
    types:
      - created
      - edited
      - category_changed

jobs:
  discussionToFile:
    runs-on: ubuntu-latest
    if: ${{ github.event.discussion.category.slug === 'blog-posts' }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ github.event.discussion.body }}" > ./blog/${{ github.event.discussion.title }}.md
          cat ./blog/${{ github.event.discussion.title }}.md
      - run: git add -a && git commit -m "Edit" && git push
