name: Discussion to file

on:
  discussion:
    types:
      - created
      - edited
      - category_changed

jobs:
  discussionToFile:
    runs-on: ubuntu-latest
    if: ${{ github.event.discussion.category.slug == 'blog-posts' }}
    steps:
      - uses: actions/checkout@v3
      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: ./blog/${{ github.event.discussion.number }}.md
          contents: ${{ fromJSON(github.event.discussion.body) }}
          write-mode: overwrite
      # - run: cat event.json
      # - run: cat event.json | jq -r '.body' > ./blog/${{ github.event.discussion.number }}.md
      - run: cat ./blog/${{ github.event.discussion.number }}.md
      # - run: rm -f event.json
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: 'Overwritten by Github Actions - ${date}'
