name: Discussion to file

on:
  discussion:
    types:
      - created
      - edited
      - labeled

jobs:
  discussionToFile:
    runs-on: ubuntu-latest
    #if: ${{ github.event.discussion.category.name === 'Blog' }}
    steps:
    - run: echo ${{ toJSON(github.event) }}
