name: Test if file exists

on:
  push:

jobs:
  file-exists:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - run: git fetch --prune --unshallow --tags
    - id: file-exists
      run: test -f test && echo "version=$(cat test)" >> $GITHUB_OUTPUT | true
    - id: file-does-not-exist
      run: test -f unknown && echo "version=$(cat unknown)" >> $GITHUB_OUTPUT | true
      continue-on-error: true

    - name: Run if yes
      if: ${{ steps.file-exists.outputs.version }}
      run: echo Yep

    - name: Run if nope
      if: ${{ steps.file-does-not-exist.outputs.version }}
      run: echo Nope

