name: mkcert

on:
  push:

jobs:
  mkcert:
    runs-on: ubuntu-latest
    steps:
      - name: Install mkcert
        run: |
          sudo apt install libnss3-tools
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
          chmod +x mkcert-v*-linux-amd64
          sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
          echo "mkcert version: $(mkcert -version)"
      - name: Install root CA
        run: mkcert -install
      - name: Generate certificates
        run: mkcert example.com "*.example.com" example.test localhost 127.0.0.1 ::1
