name: Ship it

on:
  workflow_dispatch:

jobs:
  ship-it:
    name: Ship it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          # Ensure full history is fetched to have a clear
          # path between main and clever
          fetch-depth: 0
          ref: main

      - name: Checkout clever branch
        run: |
          git fetch origin clever
          git checkout clever

      - name: Log commits to be shipped
        run: git log --oneline clever..main

      - name: Fast-forward clever to main
        run: git merge --ff-only main

      - name: Push updated clever to origin
        run: |
          git push origin clever
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
