name: Snapshot release
run-name: 'Snapshot release ${{ inputs.version }}'

on:
  workflow_dispatch:
    inputs:
      version:
        description: Base version to use for the release
        required: true
        type: string
env:
  FORCE_COLOR: 3 # Diplay chalk colors

jobs:
  snapshot:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Generate snapshot version
        id: version
        run: |
          version="${{inputs.version}}-snapshot.$(date +%Y-%m-%d).$(echo $GITHUB_SHA | cut -c1-8)"
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "::notice title=Version::${version}"
      - name: Display release tag
        run: echo "::notice title=Version (ext)::${{ steps.version.outputs.version }}"
