name: Snapshot release
run-name: 'Snapshot release ${{ github.ref_name }}'

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 3 # Diplay chalk colors

jobs:
  snapshot:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
