name: Display PR env

on:
  push:

jobs:
  echoPREnv:
    runs-on: ubuntu-latest
    steps:
    - id: tag
      name: Generate release tag
      run: echo "::set-output name=value::${{ github.ref_name }}.$(date +%Y-%m-%d_%H:%M:%S).$(echo $GITHUB_SHA | cut -c1-8)"
    - run: echo ${{ steps.tag.outputs.value }}
