name: Display PR env

on:
  push:

jobs:
  echoPREnv:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'prod' || github.ref_name == 'staging' }}
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - id: tag
      name: Generate release tag
      run: echo "::set-output name=value::${{ github.ref_name }}.$(date +%Y-%m-%d_%H.%M.%S)@$(echo $GITHUB_SHA | cut -c1-8)"
    - run: echo ${{ steps.tag.outputs.value }}
    - run: echo ${{ github.ref_name == 'prod' && 'production' || 'staging' }}
    - uses: hole19/git-tag-action@67be507b7332465ace778ee3dad62657482fedfb
      env:
        TAG: ${{ steps.tag.outputs.value }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Gets latest created release info
      id: latest_release_info
      uses: jossef/action-latest-release-info@v1.1.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Generate release notes
      id: release_notes
      uses: fresa/release-notes-generator@main
      with:
        version: ${{ steps.tag.outputs.value }}
        from_ref_exclusive: tags/${{ steps.latest_release_info.outputs.tag_name }}
        to_ref_inclusive: ${{ steps.tag.outputs.value }}
    - uses: softprops/action-gh-release@master
      name: Publish GitHub release
      with:
        name: ${{ steps.tag.outputs.value }}
        tag_name: ${{ steps.tag.outputs.value }}
        body: ${{ steps.release_notes.output.release_notes }}
